//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Master
    {
        public int Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Cast { get; set; }
    }
}
